#!/usr/bin/python3
import os, json
import subprocess

def getoutput(cmd, cwd):
   e_code, output = subprocess.getstatusoutput(f"cd {cwd}; {cmd}")
   ret = output if e_code == 0 else None
   return ret if ret != "" else None

"""
git show -s --no-color --pretty='%S -- %H -- %D -- %s'
git branch --show-current # current branch
git tag --points-at HEAD # current tag
git show -s --format="%H" # current commit
git rev-parse --abbrev-ref master@{upstream} # tracking branch of master branch
"""

if __name__ == "__main__":
   g3d_config_fn = "./test.g3d.json"
   with open(g3d_config_fn, 'r') as f:
      repos = json.load(f)

   for repo in repos:
      #print(repo)
      #cmd = f"git clone {repo['url']} -b {repo['branch']} {repo['dir_name']}"
      cmd = f"git clone {repo['url']} {repo['dir_name']}"
      print(cmd)
      os.system(cmd)
      
      
